USE store_front;

INSERT INTO users(first_name, middle_name, last_name, email, user_type) VALUES
('Alice', '', 'Johnson', 'alice.johnson@example.com', 'customer'),
('Bob', '', 'Smith', 'bob.smith@example.com', 'customer'),
('Charlie', '', 'Brown', 'charlie.brown@example.com', 'customer'),
('Diana', '', 'Prince', 'diana.prince@example.com', 'administrator'),
('Ethan', '', 'Hunt', 'ethan.hunt@example.com', 'customer'),
('Fiona', '', 'Green', 'fiona.green@example.com', 'customer'),
('George', '', 'Washington', 'george.washington@example.com', 'customer'),
('Hannah', '', 'Montana', 'hannah.montana@example.com', 'customer'),
('Ian', '', 'Malcolm', 'ian.malcolm@example.com', 'administrator'),
('Julia', '', 'Roberts', 'julia.roberts@example.com', 'customer'),
('Kevin', '', 'Bacon', 'kevin.bacon@example.com', 'customer'),
('Laura', '', 'Croft', 'laura.croft@example.com', 'customer'),
('Mike', '', 'Wazowski', 'mike.wazowski@example.com', 'customer'),
('Nina', '', 'Simone', 'nina.simone@example.com', 'customer'),
('Oscar', '', 'Wilde', 'oscar.wilde@example.com', 'administrator'),
('Paula', '', 'Abdul', 'paula.abdul@example.com', 'customer'),
('Quentin', '', 'Tarantino', 'quentin.tarantino@example.com', 'customer'),
('Rachel', '', 'Green', 'rachel.green@example.com', 'customer'),
('Steve', '', 'Jobs', 'steve.jobs@example.com', 'administrator'),
('Tina', '', 'Fey', 'tina.fey@example.com', 'customer'),
('Ursula', 'K. Le', 'Guin', 'ursula.leguin@example.com', 'customer'),
('Victor', '', 'Hugo', 'victor.hugo@example.com', 'customer'),
('Wendy', '', 'Williams', 'wendy.williams@example.com', 'customer'),
('Xena', '', 'Warrior', 'xena.warrior@example.com', 'administrator'),
('Yoda', '', 'Jedi', 'yoda.jedi@example.com', 'customer'),
('Zara', '', 'Larsson', 'zara.larsson@example.com', 'customer'),
('Alice', '', 'Cooper', 'alice.cooper@example.com', 'customer'),
('Bob', '', 'Marley', 'bob.marley@example.com', 'customer'),
('Charlie', '', 'Chaplin', 'charlie.chaplin@example.com', 'customer'),
('Daisy', '', 'Ridley', 'daisy.ridley@example.com', 'administrator'),
('Eli', '', 'Manning', 'eli.manning@example.com', 'customer'),
('Felicity', '', 'Jones', 'felicity.jones@example.com', 'customer'),
('Gordon', '', 'Ramsay', 'gordon.ramsay@example.com', 'customer'),
('Hugh', '', 'Jackman', 'hugh.jackman@example.com', 'customer'),
('Isla', '', 'Fisher', 'isla.fisher@example.com', 'administrator'),
('Jack', '', 'Black', 'jack.black@example.com', 'customer'),
('Kylie', '', 'Jenner', 'kylie.jenner@example.com', 'customer'),
('Liam', '', 'Neeson', 'liam.neeson@example.com', 'customer'),
('Megan', '', 'Fox', 'megan.fox@example.com', 'customer'),
('Nicolas', '', 'Cage', 'nicolas.cage@example.com', 'administrator'),
('Olivia', '', 'Wilde', 'olivia.wilde@example.com', 'customer'),
('Pablo', '', 'Picasso', 'pablo.picasso@example.com', 'customer'),
('Queen', '', 'Latifah', 'queen.latifah@example.com', 'customer'),
('Ryan', '', 'Gosling', 'ryan.gosling@example.com', 'customer'),
('Selena', '', 'Gomez', 'selena.gomez@example.com', 'administrator'),
('Tom', '', 'Hanks', 'tom.hanks@example.com', 'customer'),
('Uma', '', 'Thurman', 'uma.thurman@example.com', 'customer'),
('Vin', '', 'Diesel', 'vin.diesel@example.com', 'customer'),
('Will', '', 'Smith', 'will.smith@example.com', 'administrator'),
('Xander', '', 'Cage', 'xander.cage@example.com', 'customer'),
('Yasmine', '', 'Bleeth', 'yasmine.bleeth@example.com', 'customer'),
('Zach', '', 'Galifianakis', 'zach.galifianakis@example.com', 'customer'),
('Ava', '', 'Gardner', 'ava.gardner@example.com', 'customer'),
('Brad', '', 'Pitt', 'brad.pitt@example.com', 'administrator'),
('Cameron', '', 'Diaz', 'cameron.diaz@example.com', 'customer'),
('Daniel', '', 'Craig', 'daniel.craig@example.com', 'customer'),
('Eva', '', 'Mendes', 'eva.mendes@example.com', 'customer'),
('Freddie', '', 'Mercury', 'freddie.mercury@example.com', 'administrator'),
('Gina', '', 'Rodriguez', 'gina.rodriguez@example.com', 'customer'),
('Henry', '', 'Cavill', 'henry.cavill@example.com', 'customer'),
('Isabella', '', 'Rossellini', 'isabella.rossellini@example.com', 'customer'),
('James', '', 'Dean', 'james.dean@example.com', 'administrator'),
('Katherine', '', 'Hepburn', 'katherine.hepburn@example.com', 'customer'),
('Leonardo', '', 'DiCaprio', 'leonardo.dicaprio@example.com', 'customer'),
('Meryl', '', 'Streep', 'meryl.streep@example.com', 'customer'),
('Natalie', '', 'Portman', 'natalie.portman@example.com', 'administrator'),
('Owen', '', 'Wilson', 'owen.wilson@example.com', 'customer'),
('Penelope', '', 'Cruz', 'penelope.cruz@example.com', 'customer'),
('Quincy', '', 'Jones', 'quincy.jones@example.com', 'customer'),
('Rihanna', '', 'Fenty', 'rihanna.fenty@example.com', 'administrator'),
('Sharon', '', 'Stone', 'sharon.stone@example.com', 'customer'),
('Tina', '', 'Turner', 'tina.turner@example.com', 'customer'),
('Usher', '', 'Raymond', 'usher.raymond@example.com', 'customer'),
('Vera', '', 'Wang', 'vera.wang@example.com', 'administrator'),
('Whitney', '', 'Houston', 'whitney.houston@example.com', 'customer'),
('Xiomara', '', 'Castro', 'xiomara.castro@example.com', 'customer'),
('Yoko', '', 'Ono', 'yoko.ono@example.com', 'customer'),
('Zoe', '', 'Saldana', 'zoe.saldana@example.com', 'administrator');

INSERT INTO categories (name, parent_category_id) VALUES
('Electronics', 0),
('Clothing', 0),
('Stationary', 0),
('Kitchenware', 0),
('Sports', 0),
('Healthcare', 0),
('Mobile Phones', 1),
('Laptops', 1),
('AC', 1),
('TV', 1),
('Speakers and Earphones', 1),
('T Shirts', 2),
('Shirts', 2),
('Pants', 2),
('Jeans', 2),
('Socks', 2),
('Caps', 2),
('Books', 3),
('Pens', 3),
('Colors', 3),
('Knife', 4),
('Utensils', 4),
('Oven', 4),
('Stove', 4),
('Bat', 5),
('Ball', 5),
('Moisturiser', 6),
('Cold Cream', 6),
('Face Pack', 6),
('Face Wash', 6),
('Handwash', 6),
('Soap', 6),
('Shampoo', 6);

INSERT INTO products (name, category, price, stock) VALUES
('Product A', 1, 100, 50),
('Product B', 13, 150, 30),
('Product C', 1, 200, 20),
('Product D', 4, 250, 15),
('Product E', 5, 300, 10),
('Product F', 4, 120, 40),
('Product G', 5, 180, 25),
('Product H', 4, 220, 35),
('Product I', 8, 90, 60),
('Product J', 4, 130, 45),
('Product K', 21, 160, 55),
('Product L', 5, 210, 20),
('Product M', 8, 240, 15),
('Product N', 4, 270, 5),
('Product O', 8, 300, 8),
('Product P', 19, 110, 50),
('Product Q', 1, 140, 30),
('Product R', 2, 190, 25),
('Product S', 4, 230, 35),
('Product T', 1, 80, 60),
('Product U', 2, 170, 40),
('Product V', 1, 200, 20),
('Product W', 2, 250, 15),
('Product X', 8, 300, 10),
('Product Y', 2, 120, 40),
('Product Z', 5, 150, 30),
('Product AA', 6, 180, 25),
('Product AB', 6, 210, 20),
('Product AC', 6, 240, 15),
('Product AD', 7, 270, 5),
('Product AE', 14, 300, 8),
('Product AF', 7, 110, 50),
('Product AG', 3, 140, 30),
('Product AH', 6, 190, 25),
('Product AI', 19, 230, 35),
('Product AJ', 14, 80, 60),
('Product AK', 16, 170, 40),
('Product AL', 19, 200, 20),
('Product AM', 15, 250, 15),
('Product AN', 3, 300, 10),
('Product AO', 9, 120, 40),
('Product AP', 3, 150, 30),
('Product AQ', 10, 180, 25),
('Product AR', 18, 210, 20),
('Product AS', 16, 240, 15),
('Product AT', 10, 270, 5),
('Product AU', 17, 300, 8),
('Product AV', 3, 110, 50),
('Product AW', 9, 140, 30),
('Product AX', 7, 190, 25),
('Product AY', 7, 230, 35),
('Product AZ', 7, 80, 60),
('Product BA', 11, 170, 40),
('Product BB', 17, 200, 20),
('Product BC', 8, 250, 15),
('Product BD', 8, 300, 10),
('Product BE', 9, 120, 40),
('Product BF', 12, 150, 30),
('Product BG', 9, 180, 25),
('Product BH', 3, 210, 20);

INSERT INTO images (product_id, image_url) VALUES
(1, 'https://example.com/images/product1.jpg'),
(1 ,'https://example.com/images/product2.jpg'),
(2 ,'https://example.com/images/product3.jpg'),
(3 ,'https://example.com/images/product4.jpg'),
(4 ,'https://example.com/images/product5.jpg'),
(5 ,'https://example.com/images/product6.jpg'),
(5 ,'https://example.com/images/product7.jpg'),
(5 ,'https://example.com/images/product8.jpg'),
(6 ,'https://example.com/images/product9.jpg'),
(7 ,'https://example.com/images/product10.jpg'),
(8 ,'https://example.com/images/product11.jpg'),
(9 ,'https://example.com/images/product12.jpg'),
(10 ,'https://example.com/images/product13.jpg'),
(11 ,'https://example.com/images/product14.jpg'),
(11 ,'https://example.com/images/product15.jpg'),
(12 ,'https://example.com/images/product16.jpg'),
(12 ,'https://example.com/images/product17.jpg'),
(13 ,'https://example.com/images/product18.jpg'),
(14 ,'https://example.com/images/product19.jpg'),
(14 ,'https://example.com/images/product20.jpg'),
(14 ,'https://example.com/images/product21.jpg'),
(14 ,'https://example.com/images/product22.jpg'),
(15 ,'https://example.com/images/product23.jpg'),
(16 ,'https://example.com/images/product24.jpg'),
(17 ,'https://example.com/images/product25.jpg'),
(18 ,'https://example.com/images/product26.jpg'),
(19 ,'https://example.com/images/product27.jpg'),
(20 ,'https://example.com/images/product28.jpg'),
(21 ,'https://example.com/images/product29.jpg'),
(22 ,'https://example.com/images/product30.jpg'),
(23 ,'https://example.com/images/product31.jpg'),
(24 ,'https://example.com/images/product32.jpg'),
(25 ,'https://example.com/images/product33.jpg'),
(26 ,'https://example.com/images/product34.jpg'),
(27 ,'https://example.com/images/product35.jpg'),
(28 ,'https://example.com/images/product36.jpg'),
(29 ,'https://example.com/images/product37.jpg'),
(30 ,'https://example.com/images/product38.jpg'),
(31 ,'https://example.com/images/product39.jpg'),
(32 ,'https://example.com/images/product40.jpg'),
(33 ,'https://example.com/images/product41.jpg'),
(34 ,'https://example.com/images/product42.jpg'),
(35 ,'https://example.com/images/product43.jpg'),
(36 ,'https://example.com/images/product44.jpg'),
(37 ,'https://example.com/images/product45.jpg'),
(38 ,'https://example.com/images/product46.jpg'),
(39 ,'https://example.com/images/product47.jpg'),
(40 ,'https://example.com/images/product48.jpg'),
(41 ,'https://example.com/images/product49.jpg'),
(42 ,'https://example.com/images/product50.jpg'),
(43 ,'https://example.com/images/product51.jpg'),
(44 ,'https://example.com/images/product52.jpg'),
(45 ,'https://example.com/images/product53.jpg'),
(46 ,'https://example.com/images/product54.jpg'),
(47 ,'https://example.com/images/product55.jpg'),
(48 ,'https://example.com/images/product56.jpg'),
(49 ,'https://example.com/images/product57.jpg'),
(50 ,'https://example.com/images/product58.jpg'),
(51 ,'https://example.com/images/product59.jpg'),
(52 ,'https://example.com/images/product60.jpg'),
(53 ,'https://example.com/images/product61.jpg'),
(54 ,'https://example.com/images/product62.jpg'),
(55 ,'https://example.com/images/product63.jpg'),
(56 ,'https://example.com/images/product64.jpg'),
(57 ,'https://example.com/images/product65.jpg'),
(58 ,'https://example.com/images/product66.jpg'),
(59 ,'https://example.com/images/product67.jpg'),
(60 ,'https://example.com/images/product68.jpg');

INSERT INTO zipcodes (zipcode_id, city, state) VALUES
("62701", "Springfield", "Illinois"),
("53703", "Madison", "Wisconsin"),
("73301", "Austin", "Texas"),
("98101", "Seattle", "Washington"),
("80201", "Denver", "Colorado"),
("85001", "Phoenix", "Arizona"),
("97201", "Portland", "Oregon"),
("33101", "Miami", "Florida"),
("30301", "Atlanta", "Georgia"),
("2101", "Boston", "Massachusetts"),
("10001", "New York", "New York"),
("90001", "Los Angeles", "California"),
("60601", "Chicago", "Illinois"),
("94101", "San Francisco", "California"),
("75201", "Dallas", "Texas"),
("77001", "Houston", "Texas"),
("19101", "Philadelphia", "Pennsylvania"),
("92101", "San Diego", "California"),
("89101", "Las Vegas", "Nevada"),
("32801", "Orlando", "Florida"),
("28201", "Charlotte", "North Carolina"),
("46201", "Indianapolis", "Indiana"),
("43201", "Columbus", "Ohio"),
("37201", "Nashville", "Tennessee"),
("21201", "Baltimore", "Maryland"),
("53201", "Milwaukee", "Wisconsin"),
("64101", "Kansas City", "Missouri"),
("84101", "Salt Lake City", "Utah"),
("45201", "Cincinnati", "Ohio"),
("23450", "Virginia Beach", "Virginia"),
("85701", "Tucson", "Arizona"),
("93701", "Fresno", "California"),
("95801", "Sacramento", "California"),
("90801", "Long Beach", "California"),
("66101", "Kansas City", "Kansas"),
("85201", "Mesa", "Arizona"),
("23451", "Virginia Beach", "Virginia"),
("30302", "Atlanta", "Georgia"),
("80901", "Colorado Springs", "Colorado"),
("68101", "Omaha", "Nebraska"),
("27601", "Raleigh", "North Carolina"),
("33102", "Miami", "Florida"),
("44101", "Cleveland", "Ohio"),
("74101", "Tulsa", "Oklahoma"),
("94601", "Oakland", "California"),
("55401", "Minneapolis", "Minnesota"),
("67201", "Wichita", "Kansas"),
("70112", "New Orleans", "Louisiana"),
("76010", "Arlington", "Texas"),
("93301", "Bakersfield", "California"),
("33601", "Tampa", "Florida"),
("96801", "Honolulu", "Hawaii"),
("92801", "Anaheim", "California"),
("92701", "Santa Ana", "California"),
("78401", "Corpus Christi", "Texas"),
("92501", "Riverside", "California"),
("95201", "Stockton", "California"),
("89014", "Henderson", "Nevada"),
("63101", "St. Louis", "Missouri"),
("15201", "Pittsburgh", "Pennsylvania"),
("45202", "Cincinnati", "Ohio"),
("99501", "Anchorage", "Alaska"),
("27401", "Greensboro", "North Carolina"),
("75023", "Plano", "Texas"),
("68501", "Lincoln", "Nebraska"),
("32802", "Orlando", "Florida"),
("91910", "Chula Vista", "California"),
("7302", "Jersey City", "New Jersey"),
("76101", "Fort Worth", "Texas"),
("14201", "Buffalo", "New York"),
("55101", "St. Paul", "Minnesota"),
("85224", "Chandler", "Arizona"),
("78040", "Laredo", "Texas"),
("53704", "Madison", "Wisconsin"),
("27701", "Durham", "North Carolina"),
("92602", "Irvine", "California"),
("23320", "Chesapeake", "Virginia"),
("85250", "Scottsdale", "Arizona"),
("91201", "Glendale", "California"),
("89501", "Reno", "Nevada"),
("85233", "Gilbert", "Arizona"),
("33010", "Hialeah", "Florida"),
("75040", "Garland", "Texas"),
("83701", "Boise", "Idaho"),
("70801", "Baton Rouge", "Louisiana"),
("32301", "Tallahassee", "Florida"),
("50301", "Des Moines", "Iowa"),
("36601", "Mobile", "Alabama"),
("49501", "Grand Rapids", "Michigan"),
("84102", "Salt Lake City", "Utah"),
("92647", "Huntington Beach", "California"),
("66204", "Overland Park", "Kansas"),
("37901", "Knoxville", "Tennessee"),
("1601", "Worcester", "Massachusetts"),
("98660", "Vancouver", "Washington"),
("85280", "Tempe", "Arizona"),
("33904", "Cape Coral", "Florida"),
("57101", "Sioux Falls", "South Dakota"),
("1101", "Springfield", "Massachusetts"),
("61601", "Peoria", "Illinois"),
("39201", "Jackson", "Mississippi");


