USE store_front;

INSERT INTO users(first_name, middle_name, last_name, email, user_type) VALUES
('Alice', '', 'Johnson', 'alice.johnson@example.com', 'customer'),
('Bob', '', 'Smith', 'bob.smith@example.com', 'customer'),
('Charlie', '', 'Brown', 'charlie.brown@example.com', 'customer'),
('Diana', '', 'Prince', 'diana.prince@example.com', 'administrator'),
('Ethan', '', 'Hunt', 'ethan.hunt@example.com', 'customer'),
('Fiona', '', 'Green', 'fiona.green@example.com', 'customer'),
('George', '', 'Washington', 'george.washington@example.com', 'customer'),
('Hannah', '', 'Montana', 'hannah.montana@example.com', 'customer'),
('Ian', '', 'Malcolm', 'ian.malcolm@example.com', 'administrator'),
('Julia', '', 'Roberts', 'julia.roberts@example.com', 'customer'),
('Kevin', '', 'Bacon', 'kevin.bacon@example.com', 'customer'),
('Laura', '', 'Croft', 'laura.croft@example.com', 'customer'),
('Mike', '', 'Wazowski', 'mike.wazowski@example.com', 'customer'),
('Nina', '', 'Simone', 'nina.simone@example.com', 'customer'),
('Oscar', '', 'Wilde', 'oscar.wilde@example.com', 'administrator'),
('Paula', '', 'Abdul', 'paula.abdul@example.com', 'customer'),
('Quentin', '', 'Tarantino', 'quentin.tarantino@example.com', 'customer'),
('Rachel', '', 'Green', 'rachel.green@example.com', 'customer'),
('Steve', '', 'Jobs', 'steve.jobs@example.com', 'administrator'),
('Tina', '', 'Fey', 'tina.fey@example.com', 'customer'),
('Ursula', 'K. Le', 'Guin', 'ursula.leguin@example.com', 'customer'),
('Victor', '', 'Hugo', 'victor.hugo@example.com', 'customer'),
('Wendy', '', 'Williams', 'wendy.williams@example.com', 'customer'),
('Xena', '', 'Warrior', 'xena.warrior@example.com', 'administrator'),
('Yoda', '', 'Jedi', 'yoda.jedi@example.com', 'customer'),
('Zara', '', 'Larsson', 'zara.larsson@example.com', 'customer'),
('Alice', '', 'Cooper', 'alice.cooper@example.com', 'customer'),
('Bob', '', 'Marley', 'bob.marley@example.com', 'customer'),
('Charlie', '', 'Chaplin', 'charlie.chaplin@example.com', 'customer'),
('Daisy', '', 'Ridley', 'daisy.ridley@example.com', 'administrator'),
('Eli', '', 'Manning', 'eli.manning@example.com', 'customer'),
('Felicity', '', 'Jones', 'felicity.jones@example.com', 'customer'),
('Gordon', '', 'Ramsay', 'gordon.ramsay@example.com', 'customer'),
('Hugh', '', 'Jackman', 'hugh.jackman@example.com', 'customer'),
('Isla', '', 'Fisher', 'isla.fisher@example.com', 'administrator'),
('Jack', '', 'Black', 'jack.black@example.com', 'customer'),
('Kylie', '', 'Jenner', 'kylie.jenner@example.com', 'customer'),
('Liam', '', 'Neeson', 'liam.neeson@example.com', 'customer'),
('Megan', '', 'Fox', 'megan.fox@example.com', 'customer'),
('Nicolas', '', 'Cage', 'nicolas.cage@example.com', 'administrator'),
('Olivia', '', 'Wilde', 'olivia.wilde@example.com', 'customer'),
('Pablo', '', 'Picasso', 'pablo.picasso@example.com', 'customer'),
('Queen', '', 'Latifah', 'queen.latifah@example.com', 'customer'),
('Ryan', '', 'Gosling', 'ryan.gosling@example.com', 'customer'),
('Selena', '', 'Gomez', 'selena.gomez@example.com', 'administrator'),
('Tom', '', 'Hanks', 'tom.hanks@example.com', 'customer'),
('Uma', '', 'Thurman', 'uma.thurman@example.com', 'customer'),
('Vin', '', 'Diesel', 'vin.diesel@example.com', 'customer'),
('Will', '', 'Smith', 'will.smith@example.com', 'administrator'),
('Xander', '', 'Cage', 'xander.cage@example.com', 'customer'),
('Yasmine', '', 'Bleeth', 'yasmine.bleeth@example.com', 'customer'),
('Zach', '', 'Galifianakis', 'zach.galifianakis@example.com', 'customer'),
('Ava', '', 'Gardner', 'ava.gardner@example.com', 'customer'),
('Brad', '', 'Pitt', 'brad.pitt@example.com', 'administrator'),
('Cameron', '', 'Diaz', 'cameron.diaz@example.com', 'customer'),
('Daniel', '', 'Craig', 'daniel.craig@example.com', 'customer'),
('Eva', '', 'Mendes', 'eva.mendes@example.com', 'customer'),
('Freddie', '', 'Mercury', 'freddie.mercury@example.com', 'administrator'),
('Gina', '', 'Rodriguez', 'gina.rodriguez@example.com', 'customer'),
('Henry', '', 'Cavill', 'henry.cavill@example.com', 'customer'),
('Isabella', '', 'Rossellini', 'isabella.rossellini@example.com', 'customer'),
('James', '', 'Dean', 'james.dean@example.com', 'administrator'),
('Katherine', '', 'Hepburn', 'katherine.hepburn@example.com', 'customer'),
('Leonardo', '', 'DiCaprio', 'leonardo.dicaprio@example.com', 'customer'),
('Meryl', '', 'Streep', 'meryl.streep@example.com', 'customer'),
('Natalie', '', 'Portman', 'natalie.portman@example.com', 'administrator'),
('Owen', '', 'Wilson', 'owen.wilson@example.com', 'customer'),
('Penelope', '', 'Cruz', 'penelope.cruz@example.com', 'customer'),
('Quincy', '', 'Jones', 'quincy.jones@example.com', 'customer'),
('Rihanna', '', 'Fenty', 'rihanna.fenty@example.com', 'administrator'),
('Sharon', '', 'Stone', 'sharon.stone@example.com', 'customer'),
('Tina', '', 'Turner', 'tina.turner@example.com', 'customer'),
('Usher', '', 'Raymond', 'usher.raymond@example.com', 'customer'),
('Vera', '', 'Wang', 'vera.wang@example.com', 'administrator'),
('Whitney', '', 'Houston', 'whitney.houston@example.com', 'customer'),
('Xiomara', '', 'Castro', 'xiomara.castro@example.com', 'customer'),
('Yoko', '', 'Ono', 'yoko.ono@example.com', 'customer'),
('Zoe', '', 'Saldana', 'zoe.saldana@example.com', 'administrator');

INSERT INTO categories (name, parent_category_id) VALUES
('Electronics', 0),
('Clothing', 0),
('Stationary', 0),
('Kitchenware', 0),
('Sports', 0),
('Healthcare', 0),
('Mobile Phones', 1),
('Laptops', 1),
('AC', 1),
('TV', 1),
('Speakers and Earphones', 1),
('T Shirts', 2),
('Shirts', 2),
('Pants', 2),
('Jeans', 2),
('Socks', 2),
('Caps', 2),
('Books', 3),
('Pens', 3),
('Colors', 3),
('Knife', 4),
('Utensils', 4),
('Oven', 4),
('Stove', 4),
('Bat', 5),
('Ball', 5),
('Moisturiser', 6),
('Cold Cream', 6),
('Face Pack', 6),
('Face Wash', 6),
('Handwash', 6),
('Soap', 6),
('Shampoo', 6);

INSERT INTO products (name, category, price, stock) VALUES
('Product A', 1, 100, 50),
('Product B', 13, 150, 30),
('Product C', 1, 200, 20),
('Product D', 4, 250, 15),
('Product E', 5, 300, 10),
('Product F', 4, 120, 40),
('Product G', 5, 180, 25),
('Product H', 4, 220, 35),
('Product I', 8, 90, 60),
('Product J', 4, 130, 45),
('Product K', 21, 160, 55),
('Product L', 5, 210, 20),
('Product M', 8, 240, 15),
('Product N', 4, 270, 5),
('Product O', 8, 300, 8),
('Product P', 19, 110, 50),
('Product Q', 1, 140, 30),
('Product R', 2, 190, 25),
('Product S', 4, 230, 35),
('Product T', 1, 80, 60),
('Product U', 2, 170, 40),
('Product V', 1, 200, 20),
('Product W', 2, 250, 15),
('Product X', 8, 300, 10),
('Product Y', 2, 120, 40),
('Product Z', 5, 150, 30),
('Product AA', 6, 180, 25),
('Product AB', 6, 210, 20),
('Product AC', 6, 240, 15),
('Product AD', 7, 270, 5),
('Product AE', 14, 300, 8),
('Product AF', 7, 110, 50),
('Product AG', 3, 140, 30),
('Product AH', 6, 190, 25),
('Product AI', 19, 230, 35),
('Product AJ', 14, 80, 60),
('Product AK', 16, 170, 40),
('Product AL', 19, 200, 20),
('Product AM', 15, 250, 15),
('Product AN', 3, 300, 10),
('Product AO', 9, 120, 40),
('Product AP', 3, 150, 30),
('Product AQ', 10, 180, 25),
('Product AR', 18, 210, 20),
('Product AS', 16, 240, 15),
('Product AT', 10, 270, 5),
('Product AU', 17, 300, 8),
('Product AV', 3, 110, 50),
('Product AW', 9, 140, 30),
('Product AX', 7, 190, 25),
('Product AY', 7, 230, 35),
('Product AZ', 7, 80, 60),
('Product BA', 11, 170, 40),
('Product BB', 17, 200, 20),
('Product BC', 8, 250, 15),
('Product BD', 8, 300, 10),
('Product BE', 9, 120, 40),
('Product BF', 12, 150, 30),
('Product BG', 9, 180, 25),
('Product BH', 3, 210, 20);


