/*
 * This source file was generated by the Gradle 'init' task
 */
package jdbc;

import java.sql.*;

public class App {
    static final String DATABASE_NAME = "store_front";
    static final String DATABASE_URL = "jdbc:mysql://localhost/" + DATABASE_NAME;
    static final String USER = "root";
    static final String PASSWORD = "root";
    
    public static void main(String[] args) {
        try {
            String QUERY = "SELECT first_name, last_name FROM users";
            Connection conn = DriverManager.getConnection(DATABASE_URL, USER, PASS);
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(QUERY);
            // Extract data from result set
            while (rs.next()) {
                // Retrieve by column name
                System.out.println(rs.getString("first_name") + " " + rs.getString("last_name"));
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
