/*
 * This source file was generated by the Gradle 'init' task
 */
package jdbc;

import java.sql.*;

public class App {
    static final String DATABASE_URL = "jdbc:mysql://localhost/store_front";
    static final String USER = "root";
    static final String PASS = "root";
    static final String QUERY = "SELECT first_name, last_name FROM users";

    public static void main(String[] args) {

        try {
            // String driverClassName = "sun.jdbc.odbc.JdbcOdbcDriver";
            // String url = "jdbc:odbc:XE";
            // String username = "root";
            // String password = "root";
            // String query = "insert into students values(109, 'bhatt')";
            // Class.forName(driverClassName);
            // Connection con = DriverManager.getConnection(
            // url, username, password);
            // Statement st = con.createStatement();
            // int count = st.executeUpdate(query);
            // System.out.println(
            // "number of rows affected by this query= "
            // + count);
            // con.close();

            Connection conn = DriverManager.getConnection(DATABASE_URL, USER, PASS);
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(QUERY);
            // Extract data from result set
            while (rs.next()) {
                // Retrieve by column name
                System.out.println(rs.getString("first_name") + " " + rs.getString("last_name"));
            }

        } catch (Exception e) {
            System.out.println(e);
        }

    }
}
